language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t ovvn/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true ovvn/docker-react yarn run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-us-east-1-577402871189"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"
